"""empty message

Revision ID: 337125b9cc86
Revises: 915c43f3cc6e
Create Date: 2024-05-31 16:32:00.978490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337125b9cc86'
down_revision = '915c43f3cc6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('mass', sa.Float(), nullable=True),
    sa.Column('hair_color', sa.String(), nullable=True),
    sa.Column('skin_color', sa.String(), nullable=True),
    sa.Column('eye_color', sa.String(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('rotation_period', sa.Float(), nullable=True),
    sa.Column('orbital_period', sa.Float(), nullable=True),
    sa.Column('gravity', sa.String(), nullable=True),
    sa.Column('population', sa.String(), nullable=True),
    sa.Column('climate', sa.String(), nullable=True),
    sa.Column('terrain', sa.String(), nullable=True),
    sa.Column('surface_water', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('classification', sa.Float(), nullable=True),
    sa.Column('designation', sa.Float(), nullable=True),
    sa.Column('language', sa.Float(), nullable=True),
    sa.Column('avg_lifespan', sa.String(), nullable=True),
    sa.Column('avg_height', sa.String(), nullable=True),
    sa.Column('hair_colors', sa.String(), nullable=True),
    sa.Column('skin_colors', sa.String(), nullable=True),
    sa.Column('eye_colors', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species')
    op.drop_table('planets')
    op.drop_table('characters')
    # ### end Alembic commands ###
